package org.talend.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-08-01T10:50:14.014+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.talend.org/service/", name = "DemoServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DemoServicePortType {

    @WebResult(name = "DemoServiceOperationResponse", targetNamespace = "http://www.talend.org/service/", partName = "parameters")
    @WebMethod(operationName = "DemoServiceOperation", action = "http://www.talend.org/service/DemoServiceOperation")
    public DemoServiceOperationResponse demoServiceOperation(
        @WebParam(partName = "parameters", name = "DemoServiceOperationRequest", targetNamespace = "http://www.talend.org/service/")
        DemoServiceOperationRequest parameters
    );
}
