//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.01 at 02:45:44 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.xmlsoap.org/wsdl/soap/", xmlns = { @XmlNs(prefix = "soap", namespaceURI = "http://schemas.xmlsoap.org/wsdl/soap/") }, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.xmlsoap.schemas.wsdl.soap;

import javax.xml.bind.annotation.XmlNs;

