//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.01 at 02:45:44 PM CST 
//

package org.xmlsoap.schemas.wsdl.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import org.xmlsoap.schemas.wsdl.TExtensibilityElement;

/**
 * <p>
 * Java class for tOperation complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tOperation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.xmlsoap.org/wsdl/}tExtensibilityElement">
 *       &lt;attribute name="soapAction" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="style" type="{http://schemas.xmlsoap.org/wsdl/soap/}tStyleChoice" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOperation")
@XmlRootElement(name = "operation")
public class TOperation extends TExtensibilityElement {

	@XmlAttribute
	@XmlSchemaType(name = "anyURI")
	protected String soapAction;
	@XmlAttribute
	protected TStyleChoice style;

	/**
	 * Gets the value of the soapAction property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSoapAction() {
		return soapAction;
	}

	/**
	 * Sets the value of the soapAction property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSoapAction(String value) {
		this.soapAction = value;
	}

	/**
	 * Gets the value of the style property.
	 * 
	 * @return possible object is {@link TStyleChoice }
	 * 
	 */
	public TStyleChoice getStyle() {
		return style;
	}

	/**
	 * Sets the value of the style property.
	 * 
	 * @param value
	 *            allowed object is {@link TStyleChoice }
	 * 
	 */
	public void setStyle(TStyleChoice value) {
		this.style = value;
	}

}
