//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.01 at 02:45:44 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2001/XMLSchema", xmlns = {
		@XmlNs(prefix = "xsd", namespaceURI = "http://www.w3.org/2001/XMLSchema"),
		@XmlNs(prefix = "tns", namespaceURI = "http://www.talend.org/service/") }, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.xmlsoap.schemas.schema;

import javax.xml.bind.annotation.XmlNs;

