//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 03:20:48 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jzventures.java6.common.j2se.salever.org")
package org.salever.j2se.common.java6.jzventures;
