package org.salever.rcp.dbSystem.client.db.model;

// Generated 2011-10-5 12:18:45 by Hibernate Tools 3.4.0.CR1

import java.util.Set;

/**
 * Card generated by hbm2java
 */
public class Card implements java.io.Serializable {

	public static final int TYPE_900M = 1;
	public static final int TYPE_2_4G = 2;
	public static final int TYPE_OTHER = 0;
	public static final int MIFARE = 3;

	public static final int STATUS_UNUSED = 0;
	public static final int STATUS_USED = 1;

	private Integer id;
	private String code;
	private int deviceType;
	private int codeWidth;
	private int status;

	public Card() {
	}

	public Card(String code, int deviceType, int codeWidth, int status) {
		this.code = code;
		this.deviceType = deviceType;
		this.codeWidth = codeWidth;
		this.status = status;
	}

	public Card(String code, int deviceType, int codeWidth, int status,
			Set customRecords, Set customCards) {
		this.code = code;
		this.deviceType = deviceType;
		this.codeWidth = codeWidth;
		this.status = status;
	}

	public String getCode() {
		return this.code;
	}

	public int getCodeWidth() {
		return this.codeWidth;
	}

	public int getDeviceType() {
		return this.deviceType;
	}

	public Integer getId() {
		return this.id;
	}

	public int getStatus() {
		return this.status;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public void setCodeWidth(int codeWidth) {
		this.codeWidth = codeWidth;
	}

	public void setDeviceType(int deviceType) {
		this.deviceType = deviceType;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
