//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.01 at 02:45:44 PM CST 
//

package org.xmlsoap.schemas.wsdl;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.xmlsoap.schemas.schema.TSchema;

/**
 * <p>
 * Java class for tTypes complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tTypes">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.xmlsoap.org/wsdl/}tExtensibleDocumented">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTypes", propOrder = { "schemas" })
@XmlRootElement(name = "types")
public class TTypes extends TExtensibleDocumented {

	@XmlElements({ @XmlElement(name = "schema", type = TSchema.class, namespace = "http://www.w3.org/2001/XMLSchema") })
	protected List<TSchema> schemas;

	public List<TSchema> getSchemas() {
		if (schemas == null) {
			schemas = new ArrayList<TSchema>();
		}
		return schemas;
	}

}
