/*******************************************************************************
 * Copyright (c) 2009 Jeff McAffer, Ed Merks and others. All rights reserved.
 * This program and the accompanying materials are made available under the 
 * terms of the Eclipse Public License v1.0 and Eclipse Distribution License v1.0 
 * which accompanies this distribution. The Eclipse Public License is available at 
 * http://www.eclipse.org/legal/epl-v10.html and the Eclipse Distribution License 
 * is available at http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors: 
 *     Jeff McAffer and Ed Merks - initial API and implementation
 *******************************************************************************/
package org.equinoxosgi.toast.backend.data.validation;

import org.equinoxosgi.toast.backend.data.IAddress;
import org.equinoxosgi.toast.backend.data.IPackage;

import java.util.Date;

/**
 * A sample validator interface for {@link org.equinoxosgi.toast.backend.data.IWaybill}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WaybillValidator {
	boolean validate();

	boolean validateId(int value);

	boolean validateItem(IPackage value);

	boolean validateReceived(Date value);

	boolean validateSent(Date value);

	boolean validateDestination(IAddress value);

	boolean validateOrigin(IAddress value);
}
