package org.salever.rcp.remoteSystem.server.model;

// Generated Jun 1, 2012 9:06:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * Card generated by hbm2java
 */
public class Card implements java.io.Serializable {

	public static final int STUDENT_TYPE = 0;
	public static final int TEACHER_TYPE = 1;
	public static final int PARENT_TYPE = 2;

	/**
	 * 未绑定
	 */
	public static final int STATUS_UNUSED = 1;

	/**
	 * 已绑定
	 */
	public static final int STATUS_USED = 2;

	/**
	 * 其他定
	 */
	public static final int STATUS_OTHER = 3;

	private Integer id;
	private String uniqueCode;
	private int type;
	private int status;

	private String owner;

	// private Set studentsForParentCardId = new HashSet(0);
	// private Set studentsForStudentCardId = new HashSet(0);
	// private Set deviceWarningMessages = new HashSet(0);
	// private Set teachers = new HashSet(0);

	public Card() {
	}

	public Card(String uniqueCode, int type) {
		this.uniqueCode = uniqueCode;
		this.type = type;
	}

	// public Card(String uniqueCode, int type, Set studentsForParentCardId,
	// Set studentsForStudentCardId, Set deviceWarningMessages,
	// Set teachers) {
	// this.uniqueCode = uniqueCode;
	// this.type = type;
	// this.studentsForParentCardId = studentsForParentCardId;
	// this.studentsForStudentCardId = studentsForStudentCardId;
	// this.deviceWarningMessages = deviceWarningMessages;
	// this.teachers = teachers;
	// }

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUniqueCode() {
		return this.uniqueCode;
	}

	public void setUniqueCode(String uniqueCode) {
		this.uniqueCode = uniqueCode;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	/**
	 * @param status
	 *            the status to set
	 */
	public void setStatus(int status) {
		this.status = status;
	}

	/**
	 * @return the status
	 */
	public int getStatus() {
		return status;
	}

	/**
	 * @param owner
	 *            the owner to set
	 */
	public void setOwner(String owner) {
		this.owner = owner;
	}

	/**
	 * @return the owner
	 */
	public String getOwner() {
		return owner;
	}

	// public Set getStudentsForParentCardId() {
	// return this.studentsForParentCardId;
	// }
	//
	// public void setStudentsForParentCardId(Set studentsForParentCardId) {
	// this.studentsForParentCardId = studentsForParentCardId;
	// }
	//
	// public Set getStudentsForStudentCardId() {
	// return this.studentsForStudentCardId;
	// }
	//
	// public void setStudentsForStudentCardId(Set studentsForStudentCardId) {
	// this.studentsForStudentCardId = studentsForStudentCardId;
	// }
	//
	// public Set getDeviceWarningMessages() {
	// return this.deviceWarningMessages;
	// }
	//
	// public void setDeviceWarningMessages(Set deviceWarningMessages) {
	// this.deviceWarningMessages = deviceWarningMessages;
	// }
	//
	// public Set getTeachers() {
	// return this.teachers;
	// }
	//
	// public void setTeachers(Set teachers) {
	// this.teachers = teachers;
	// }

}
